import enum


class UnitAbbreviation(str, enum.Enum):
    ACRE = "ACRE"
    ASMY = "ASMY"
    CY = "CY"
    DAY = "DAY"
    DOL = "DOL"
    EACH = "EACH"
    GAL = "GAL"
    HOUR = "HOUR"
    LF = "LF"
    LB = "LB"
    LS = "LS"
    MBM = "MBM"
    MGAL = "MGAL"
    PLT = "PLT"
    RDST = "RDST"
    SF = "SF"
    SY = "SY"
    SHRB = "SHRB"
    SIGS = "SIGS"
    STR = "STR"
    SYS = "SYS"
    TON = "TON"
    TREE = "TREE"
    UDAY = "UDAY"
    VINE = "VINE"


class Unit(str, enum.Enum):
    ACRE = "ACRE"
    ASSEMBLY = "ASSEMBLY"
    CU_YD = "CU YD"
    DAY = "DAY"
    DOLLAR = "DOLLAR"
    EACH = "EACH"
    GALLON = "GALLON"
    HOUR = "HOUR"
    LIN_FT = "LIN FT"
    POUND = "POUND"
    LUMP_SUM = "LUMP SUM"
    MBM = "MBM"
    M_GALLON = "M GALLON"
    PLANT = "PLANT"
    ROAD_STA = "ROAD STA"
    SQ_FT = "SQ FT"
    SQ_YD = "SQ YD"
    SHRUB = "SHRUB"
    SIGNAL_SYSTEM = "SIGNAL SYSTEM"
    STRUCTURE = "STRUCTURE"
    SYSTEM = "SYSTEM"
    TON = "TON"
    TREE = "TREE"
    UNIT_DAY = "UNIT DAY"
    VINE = "VINE"
